 

  class ResponseEnrollCounter {
    //boolean,string,obj
    constructor(FISCAL_YEAR, SEMESTER, YEAR, TYPE_COUNTER, SYSTEM_STATUS_REGISTER, SYSTEM_STATUS_ENROLLMENT, SYSTEM_STATUS_ADMIN, SYSTEM_STATUS_ALL,
        REGIS_DUEDATE, ENROLL_DUEDATE, REGIS_START_DATE, REGIS_END_DATE, ENROLL_START_DATE, ENROLL_END_DATE) {
        
        this.FISCAL_YEAR = FISCAL_YEAR;
        this.SEMESTER = SEMESTER;
        this.YEAR = YEAR;
        this.TYPE_COUNTER = TYPE_COUNTER;
        this.SYSTEM_STATUS_REGISTER = SYSTEM_STATUS_REGISTER;
        this.SYSTEM_STATUS_ENROLLMENT = SYSTEM_STATUS_ENROLLMENT;
        this.SYSTEM_STATUS_ADMIN = SYSTEM_STATUS_ADMIN;
        this.SYSTEM_STATUS_ALL = SYSTEM_STATUS_ALL;
        this.REGIS_DUEDATE = REGIS_DUEDATE;
        this.ENROLL_DUEDATE = ENROLL_DUEDATE;
        this.REGIS_START_DATE = REGIS_START_DATE;
        this.REGIS_END_DATE = REGIS_END_DATE;
        this.ENROLL_START_DATE = ENROLL_START_DATE;
        this.ENROLL_END_DATE = ENROLL_END_DATE;
    }
}
 


module.exports = ResponseEnrollCounter ;